# docker-compose.yml
services:
  db:
    image: postgres:16
    container_name: cos326_db
    environment:
      POSTGRES_USER: cos326
      POSTGRES_PASSWORD: cos326pwd
      POSTGRES_DB: employeesDB  
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cos326 -d employeesDB"]
      interval: 2s
      timeout: 2s
      retries: 20

  pgadmin: 
    image: dpage/pgadmin4:8
    container_name: cos326_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:

