version: "3.8"

services:
  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"   
      - "7687:7687"   
    environment:
      - NEO4J_AUTH=neo4j/testpassword
      - NEO4J_dbms_default__database=prac9neo4j.graphdb
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=1g
      - NEO4J_dbms_memory_pagecache_size=512m
    volumes:
      - neo4j_data:/data  

volumes:
  neo4j_data:

